[font]
normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }

[colors.primary]
background = "#1c1c1f"
foreground = "#ffffff"

[colors.normal]
black = "#241f31"
red = "#c01c28"
green = "#2ec27e"
yellow = "#f5c211"
blue = "#1e78e4"
magenta = "#9841bb"
cyan = "#0ab9cc"
white = "#c0bfbc"

[colors.bright]
black = "#5e5c64"
red = "#ed333b"
green = "#57e389"
yellow = "#f8e45c"
blue = "#51a1ff"
magenta = "#c061cb"
cyan = "#4fd2fd"
white = "#f6f5f4"
